import type { Listing } from '@/types';

export const sampleListings: Listing[] = [
  {
    id: '1',
    sellerId: 's1',
    title: 'Designer Bridal Lehenga',
    description: 'Stunning red bridal lehenga with heavy zardozi work. Perfect for wedding main event. Comes with double dupatta.',
    category: 'lehenga_choli',
    gender: 'women',
    eventTags: ['marriage'],
    customTags: ['bridal', 'heavy work', 'designer'],
    detailTags: ['zardozi', 'silk', 'heavy'],
    size: 'M',
    condition: 'good',
    pricePerDay: 2500,
    deposit: 10000,
    deliveryType: 'both',
    status: 'active',
    viewCount: 156,
    lat: 21.1702,
    lng: 72.8311,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    images: [
      { id: 'i1a', listingId: '1', url: 'https://placehold.co/400x500/E31C5F/FFFFFF?text=Red+Lehenga', order: 0 },
      { id: 'i1b', listingId: '1', url: 'https://placehold.co/400x500/C9A84C/333333?text=Details', order: 1 },
      { id: 'i1c', listingId: '1', url: 'https://placehold.co/400x500/1B4332/FFFFFF?text=Dupatta', order: 2 },
    ],
    videos: [],
    seller: {
      id: 's1',
      displayName: 'Neha Sharma',
      username: 'neha_designs',
      profileImage: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Neha',
      rating: 4.9,
      totalRentals: 42,
      memberSince: '2023-01-15'
    },
    distance: 2.5,
    _count: { reviews: 15, bookings: 28 },
    analytics: { impressions: 1205, views: 156, addToCart: 45, dateSelected: 32, checkoutStarted: 28, ordersCompleted: 28, wishlistAdded: 89, shareCount: 12 }
  },
  {
    id: '2',
    sellerId: 's2',
    title: 'Royal Blue Sherwani set',
    description: 'Elegant royal blue velvet sherwani with golden embroidery. Includes matching churidar and selectively styled dupatta.',
    category: 'sherwani',
    gender: 'men',
    eventTags: ['marriage', 'engagement'],
    customTags: ['royal', 'velvet'],
    detailTags: ['embroidery', 'velvet', 'heavy'],
    size: 'L',
    condition: 'like_new',
    pricePerDay: 1800,
    deposit: 5000,
    deliveryType: 'pickup',
    status: 'active',
    viewCount: 92,
    lat: 21.1852,
    lng: 72.8211,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    images: [
      { id: 'i2a', listingId: '2', url: 'https://placehold.co/400x500/1E3A8A/FFFFFF?text=Blue+Sherwani', order: 0 },
      { id: 'i2b', listingId: '2', url: 'https://placehold.co/400x500/D4AF37/333333?text=Embroidery', order: 1 },
    ],
    videos: [],
    seller: {
      id: 's2',
      displayName: 'Rahul Verma',
      username: 'rahul_v',
      profileImage: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Rahul',
      rating: 4.5,
      totalRentals: 12,
      memberSince: '2023-08-22'
    },
    distance: 4.1,
    _count: { reviews: 5, bookings: 9 },
    analytics: { impressions: 840, views: 92, addToCart: 15, dateSelected: 10, checkoutStarted: 9, ordersCompleted: 9, wishlistAdded: 34, shareCount: 5 }
  },
  {
    id: '3',
    sellerId: 's3',
    title: 'Pink Anarkali Suit',
    description: 'Beautiful pink anarkali with delicate mirror work. Great for sangeet and mehndi functions. Flattering silhouette with comfortable fit.',
    category: 'anarkali',
    gender: 'women',
    eventTags: ['sangeet', 'mehndi', 'festival'],
    customTags: ['handicraft', 'mirror work'],
    detailTags: ['mirror_work', 'handwork', 'light', 'georgette'],
    size: 'S',
    condition: 'like_new',
    pricePerDay: 800,
    deposit: 2500,
    deliveryType: 'delivery',
    status: 'active',
    viewCount: 89,
    lat: 21.1752,
    lng: 72.8511,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    images: [
      { id: 'i3a', listingId: '3', url: 'https://placehold.co/400x500/FFB6C1/333333?text=Anarkali+Front', order: 0 },
      { id: 'i3b', listingId: '3', url: 'https://placehold.co/400x500/FFC0CB/333333?text=Anarkali+Back', order: 1 },
      { id: 'i3c', listingId: '3', url: 'https://placehold.co/400x500/FF69B4/FFFFFF?text=Anarkali+Close', order: 2 },
    ],
    videos: [],
    seller: {
      id: 's3',
      displayName: 'Anjali Patel',
      username: 'anjali_ethnic',
      profileImage: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Anjali',
      rating: 4.8,
      totalRentals: 25,
      memberSince: '2023-06-10'
    },
    distance: 1.2,
    _count: { reviews: 12, bookings: 19 },
    analytics: { impressions: 423, views: 89, addToCart: 12, dateSelected: 8, checkoutStarted: 5, ordersCompleted: 19, wishlistAdded: 28, shareCount: 9 }
  },
  {
    id: '4',
    sellerId: 's4',
    title: 'Pastel Floral Saree',
    description: 'Lightweight organza saree with pastel floral prints and sequins border. Perfect for day events and summer weddings.',
    category: 'saree',
    gender: 'women',
    eventTags: ['casual', 'festival'],
    customTags: ['floral', 'pastel', 'organza'],
    detailTags: ['organza', 'sequins', 'light'],
    size: 'M',
    condition: 'good',
    pricePerDay: 1200,
    deposit: 3000,
    deliveryType: 'both',
    status: 'active',
    viewCount: 245,
    lat: 21.1952,
    lng: 72.8411,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    images: [
      { id: 'i4a', listingId: '4', url: 'https://placehold.co/400x500/E8F4F8/333333?text=Floral+Saree', order: 0 },
      { id: 'i4b', listingId: '4', url: 'https://placehold.co/400x500/FDF6E3/333333?text=Saree+Pallu', order: 1 },
    ],
    videos: [],
    seller: {
      id: 's4',
      displayName: 'Kriti Couture',
      username: 'kriti_c',
      profileImage: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Kriti',
      rating: 4.6,
      totalRentals: 88,
      memberSince: '2022-11-05'
    },
    distance: 5.6,
    _count: { reviews: 45, bookings: 72 },
    analytics: { impressions: 2100, views: 245, addToCart: 85, dateSelected: 70, checkoutStarted: 65, ordersCompleted: 72, wishlistAdded: 150, shareCount: 22 }
  },
  {
    id: '5',
    sellerId: 's5',
    title: 'Classic Black Jodhpuri',
    description: 'Timeless black bandhgala suit with golden buttons. Tailored fit, ideal for evening receptions and formal gatherings.',
    category: 'jodhpuri',
    gender: 'men',
    eventTags: ['corporate', 'marriage'],
    customTags: ['classic', 'formal'],
    detailTags: ['wool_blend', 'tailored', 'solid'],
    size: 'XL',
    condition: 'like_new',
    pricePerDay: 1500,
    deposit: 4500,
    deliveryType: 'pickup',
    status: 'active',
    viewCount: 67,
    lat: 21.1652,
    lng: 72.8111,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    images: [
      { id: 'i5a', listingId: '5', url: 'https://placehold.co/400x500/111111/FFFFFF?text=Black+Jodhpuri', order: 0 },
      { id: 'i5b', listingId: '5', url: 'https://placehold.co/400x500/333333/FFFFFF?text=Button+Detail', order: 1 },
    ],
    videos: [],
    seller: {
      id: 's5',
      displayName: 'Vikram Singh',
      username: 'vikram_s',
      profileImage: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Vikram',
      rating: 4.2,
      totalRentals: 8,
      memberSince: '2024-01-20'
    },
    distance: 0.8,
    _count: { reviews: 2, bookings: 5 },
    analytics: { impressions: 320, views: 67, addToCart: 8, dateSelected: 6, checkoutStarted: 5, ordersCompleted: 5, wishlistAdded: 12, shareCount: 2 }
  }
];
